version: '3'
services:
  php81:
    build: config/php81
    container_name: magento244ce_php81
    volumes:
      - ..:/var/www/html
      - /home/bruno/.ssh:/root/.ssh
    networks:
      - dev_network
  nginx:
    build: config/nginx
    container_name: magento244ce_nginx
    volumes:
      - ..:/var/www/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/includes:/etc/nginx/includes
    ports:
      - "443:443"
    networks:
      - dev_network
  varnish:
    image: varnish:latest
    container_name: magento244ce_varnish
    volumes:
      - ./config/varnish/default.vcl:/etc/varnish/default.vcl
    ports:
      - "80:80"
      - "6082:6082"
    links:
      - "nginx"
    networks:
      - dev_network
  mysql8:
    image: mysql:8
    container_name: magento244ce_mysql8
    command: mysqld --sql_mode="" --innodb-buffer-pool-size=2056M
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/dumpsmysql:/var/dumps
    environment:
      - MYSQL_ROOT_PASSWORD=pw
    networks:
      - dev_network
  redis:
    image: redis:6.2
    container_name: magento244ce_redis
    ports:
      - "6379:6379"
    networks:
      - dev_network
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: magento244ce_rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia
    networks:
      - dev_network
  elasticsearch:
    container_name: magento244ce_elasticsearch
    image: elasticsearch:7.16.3
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - discovery.type=single-node
    networks:
      - dev_network
  kibana:
    container_name: magento244ce_kibana
    image: docker.elastic.co/kibana/kibana:7.16.3
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - dev_network
  opensearch:
    container_name: magento244ce_opensearch
    image: opensearchproject/opensearch:1.2
    ports:
      - '9200:9200'
      - '9600:9600'
    environment:
      - discovery.type=single-node
    networks:
      - dev_network
  opensearch-dashboard:
    container_name: magento244ce_opensearch_dashboard
    image: opensearch-dashboards:1.2
    ports:
      - '5601:5601'
    environment:
      - discovery.type=single-node
    networks:
      - dev_network
  mailhog:
    image: mailhog/mailhog:latest
    container_name: magento244ce_mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - dev_network
  newrelic:
    image: newrelic/php-daemon
    container_name: magento244ce_newrelic
    networks:
      - dev_network
networks:
  dev_network:
    driver: bridge
