version: '3'
services:
  nginx:
    image: nginx:1.17.3
    container_name: conectouv2_nginx
    volumes:
      - ..:/var/www/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./config/nginx/includes:/etc/nginx/includes
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - dev_network
  php72:
    build: config/php
    container_name: conectouv2_php72
    volumes:
      - ..:/var/www/html
      - /home/bruno/.ssh:/root/.ssh
    networks:
      - dev_network
  varnish:
    image: varnish:latest
    container_name: conectouv2_varnish
    volumes:
      - ./config/varnish/default.vcl:/etc/varnish/default.vcl
    ports:
      - "80:80"
    links:
      - "nginx"
    networks:
      - dev_network
  mysql:
    image: mysql:5.7
    container_name: conectouv2_mysql57
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./data/dumps:/var/dumps
    environment:
      - MYSQL_ROOT_PASSWORD=pw
    networks:
      - dev_network
networks:
  dev_network:
    driver: bridge