version: '3'
services:
  nginx:
    image: nginx:1.17.3
    container_name: nginx
    volumes:
      - ..:/var/www/html
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - dev_network
  php72:
    build: docker/config/php
    container_name: php72
    volumes:
      - ..:/var/www/html
    networks:
      - dev_network
  varnish:
    image: varnish:latest
    container_name: varnish
    volumes:
      - ./config/varnish/default.vcl:/etc/varnish/default.vcl
    ports:
      - "80:80"
    links:
      - "nginx"
    networks:
      - dev_network
  mysql:
    image: mysql:5.7
    container_name: mysql57
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pw
    ports:
      - "3306:3306"
    networks:
      - dev_network
networks:
  dev_network:
    driver: bridge